'use client';

import Header from '../components/Header';

export default function TermsPage() {
  const lastUpdated = 'February 25, 2026';

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 via-gray-800 to-gray-900 text-white">
      <Header />

      <main className="pt-28 pb-20 px-4 max-w-3xl mx-auto">
        <div className="mb-10">
          <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: {lastUpdated}</p>
        </div>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Prismo ("Service"), you agree to be bound by these Terms of Service. If you do not agree,
              do not use the Service. These terms constitute a legally binding agreement between you and Prismo.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              Prismo provides financial analysis tools including valuation models, technical analysis, fundamental data,
              and AI-powered summaries. The Service is provided for <strong>informational and educational purposes only</strong>.
              Nothing in the Service constitutes investment advice, financial advice, or a recommendation to buy or sell
              any security.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Not Investment Advice</h2>
            <p className="mb-3">
              <strong>IMPORTANT — PLEASE READ CAREFULLY:</strong> Prismo is an analytical tool, not an investment advisor.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>All analysis, valuations, scores, and recommendations generated by Prismo are <strong>for informational purposes only</strong>.</li>
              <li>Past performance of any model or analysis does not guarantee future results.</li>
              <li>You are solely responsible for your own investment decisions.</li>
              <li>Prismo does not hold or apply for registration as an Investment Advisor under the Investment Advisers Act of 1940 or any state equivalent.</li>
              <li>Consult a licensed financial advisor before making investment decisions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Account Registration</h2>
            <p>
              You must be at least 18 years old to create an account. You are responsible for maintaining the security of
              your account credentials. You agree to provide accurate, current, and complete information. You are responsible
              for all activity that occurs under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Subscriptions and Billing</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Paid subscriptions are billed monthly or annually as selected at purchase.</li>
              <li>Payments are processed by Stripe. By subscribing, you agree to Stripe's terms of service.</li>
              <li>Subscriptions auto-renew unless cancelled before the renewal date.</li>
              <li>We offer a 7-day refund policy for first-time subscribers who are not satisfied.</li>
              <li>No refunds are issued for partial months or for feature non-use.</li>
              <li>We reserve the right to modify pricing with 30 days' notice to existing subscribers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any illegal purpose or in violation of any applicable laws.</li>
              <li>Scrape, harvest, or extract data from the Service by automated means without written consent.</li>
              <li>Reverse-engineer, decompile, or attempt to extract the source code of the Service.</li>
              <li>Use the Service to manipulate markets or engage in fraudulent activity.</li>
              <li>Share your account credentials with others (one account per individual).</li>
              <li>Reproduce or redistribute our analysis or data commercially without a license.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>
              All content, models, algorithms, and software in Prismo are proprietary and protected by copyright law.
              You receive a limited, non-exclusive, non-transferable license to use the Service during your subscription.
              No ownership rights are transferred.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. User Content</h2>
            <p>
              By posting analyses, diary entries, or blog posts through the Service, you grant Prismo a non-exclusive,
              worldwide, royalty-free license to use, store, and display that content in connection with the Service.
              You retain all ownership rights in your content. You are responsible for ensuring your content does not
              violate any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Data Accuracy</h2>
            <p>
              Financial data is sourced from third-party providers and may contain errors or delays. Prismo makes no
              warranty as to the accuracy, completeness, or timeliness of any data or analysis. You should verify
              critical data from primary sources before making any decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PRISMO SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO INVESTMENT LOSSES, LOSS OF PROFITS,
              OR LOSS OF DATA, ARISING FROM YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
              PRISMO'S TOTAL LIABILITY FOR ANY CLAIM SHALL NOT EXCEED THE AMOUNTS PAID BY YOU TO PRISMO IN THE
              THREE MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
              NON-INFRINGEMENT. PRISMO DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR
              FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict
              of law principles. Any disputes shall be resolved in the courts of Delaware, and you consent to
              personal jurisdiction therein.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. We will provide 30 days' notice of material changes via email.
              Continued use of the Service after the effective date of changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">14. Contact</h2>
            <p>
              Questions about these Terms: <a href="mailto:legal@prismo.app" className="text-emerald-400 hover:underline">legal@prismo.app</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
